### ISSUE TITLE
Taxonomy loader for 3.5 framework

### ISSUE THREAD

**Issue by genije** [Meaningful-Data/xbridge#10]
While trying to load taxonomy for 3.5 framework i got this error for DORA module:
```
Converting 7z to zip
7z file extracted in 8.20712685585022 s
Zip file created in 0.331 s
7z to zip conversion done in 8.538 s
Conversion done in 8.538 s
Loading module FINREP9
Module FINREP9 loaded in 0.169 s
Loading module RESOL
Module RESOL loaded in 0.059 s
Loading module RESOL_IND
Module RESOL_IND loaded in 0.049 s
Loading module RESOL_CON
Module RESOL_CON loaded in 0.049 s
Loading module CONDIS
Module CONDIS loaded in 0.101 s
Loading module REMDIS
Module REMDIS loaded in 0.005 s
Loading module FINDIS
Module FINDIS loaded in 0.002 s
Loading module ESGDIS
Module ESGDIS loaded in 0.033 s
Loading module MREL_DECISIONS
Module MREL_DECISIONS loaded in 0.001 s
Loading module MREL_TLAC
Module MREL_TLAC loaded in 0.003 s
Loading module MREL_TLAC
Module MREL_TLAC loaded in 0.003 s
Loading module MREL_TLAC
Module MREL_TLAC loaded in 0.003 s
Loading module IPU
Module IPU loaded in 0.0 s
Loading module AE
Module AE loaded in 0.016 s
Loading module SBP_IFRS9
Module SBP_IFRS9 loaded in 0.001 s
Loading module SBPIMV_CON
Module SBPIMV_CON loaded in 0.0 s
Loading module SBP_RM
Module SBP_RM loaded in 0.001 s
Loading module SBPIMV_IND
Module SBPIMV_IND loaded in 0.0 s
Loading module SBP_CR
Module SBP_CR loaded in 0.001 s
Loading module SBPIMV
Module SBPIMV loaded in 0.0 s
Loading module SBPIMV_CON
Module SBPIMV_CON loaded in 0.0 s
Loading module SBP_CR_IND
Module SBP_CR_IND loaded in 0.002 s
Loading module SBPIMV_IND
Module SBPIMV_IND loaded in 0.0 s
Loading module SBP_CR_CON
Module SBP_CR_CON loaded in 0.002 s
Loading module SBP_RM_IND
Module SBP_RM_IND loaded in 0.001 s
Loading module SBP_RM_CON
Module SBP_RM_CON loaded in 0.001 s
Loading module SBP_IFRS9
Module SBP_IFRS9 loaded in 0.002 s
Loading module SBP_RM
Module SBP_RM loaded in 0.002 s
Loading module SBP_CR
Module SBP_CR loaded in 0.001 s
Loading module SBPIMV
Module SBPIMV loaded in 0.001 s
Loading module FC
Module FC loaded in 0.003 s
Loading module DORA
Traceback (most recent call last):
  File "xbridge/taxonomy_loader.py", line 214, in <module>
    main()
  File "xbridge/taxonomy_loader.py", line 210, in main
    Taxonomy.from_taxonomy(args.input_path)
  File "xbridge/taxonomy_loader.py", line 164, in from_taxonomy
    obj.load_modules(input_path)
  File "xbridge/taxonomy_loader.py", line 122, in load_modules
    module = Module.from_taxonomy(zip_file, file_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xbridge/modules.py", line 106, in from_taxonomy
    obj.extract_tables(zip_file)
  File "xbridge/modules.py", line 69, in extract_tables
    table = Table.from_taxonomy(
            ^^^^^^^^^^^^^^^^^^^^
  File "xbridge/modules.py", line 289, in from_taxonomy
    obj.extract_variables(zip_file)
  File "xbridge/modules.py", line 271, in extract_variables
    raise KeyError(f"'datapoint' key not found in tableTemplates for code {self.code}")
KeyError: "'datapoint' key not found in tableTemplates for code B_01-01"
```

**Comment by antonio-olleros** [comment]
Hi @genije , thanks a lot for reporting this. If I'm not mistaken, you are using the new architecture, is that correct? Let us check it and we will create a new release updated to the 3.5 taxonomy

**Comment by genije** [comment]
I just read documentation for 3.5 framework and i saw that DORA is still not aplicable so when i remove DORA from modules everything works.
Sorry, i didn’t read that part.

So there is nothing to change in your code for new framework.

Regards,
Veselin

**Comment by javihern98** [comment]
Hi @genije, version 1.1 has been published supporting the EBA 4.0 Taxonomy.
